### ISSUE TITLE
[Suggestion] Use Date Picker from ox_lib for due dates

### ISSUE THREAD

**Issue by Risky-Shot** [juddisjudd/judd_invoice#2]
Hi, This is a suggestion to use [Date Picker](https://overextended.dev/ox_lib/Modules/Interface/Client/input#field-type-properties) from `ox_lib/inputDialog` to select `due date` for invoice.

**Comment by wolved** [comment]
i second this!

**Comment by juddisjudd** [comment]
> Hi, This is a suggestion to use [Date Picker](https://overextended.dev/ox_lib/Modules/Interface/Client/input#field-type-properties) from `ox_lib/inputDialog` to select `due date` for invoice.

Feel free to make a PR or fork. This was just a simple dev resource, I don't actively work on FiveM resources.
